# Generated by Django 4.2.6 on 2024-03-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eLearningApp', '0007_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
